name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '/home/runner/work/codemirror.next/codemirror.next/node_modules'
          key: ${{ runner.os }}-node-modules

      - run: node bin/cm.js install && npm test
